name: Build and upload to PyPI

on:
  merge_group:
    types: [checks_requested]

permissions:
  contents: write

jobs:
  update_version:
    name: update version
    runs-on: ubuntu-slim
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"
      - name: Update version on merge
        run:  |
            python tools/version.py "beta"
      - name: Store changes
        uses: actions/upload-artifact@v4
        with:
          name: pyproject
          path: |
            ./pyproject.toml
            ./setup.py

  update_setup:
    needs: [update_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"

      - uses: actions/download-artifact@v4
        with:
          name: pyproject
      - name: check
        run: |
          cat pyproject.toml
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "update version number"
          add: |
            - pyproject.toml
            - setup.py'
