name: Build and upload to PyPI

on:
  pull_request:
    branches:
      - 'main'


permissions:
  contents: write

jobs:
  update_version:
    name: update version
    runs-on: ubuntu-slim
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"
      - name: Update version on merge
        run: |
            python tools/version.py "beta"
      - name: Store changes
        uses: actions/upload-artifact@v4
        with:
          name: pyproject
          path: |
            ./pyproject.toml
            ./setup.py

  update_setup:
    needs: [update_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"
          ssh-key: ${{ secrets.BUILD }}
      - uses: actions/download-artifact@v4
        with:
          name: pyproject
      - name: check
        run: |
          cat pyproject.toml

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"
